package com.blogspot.ostas.leetcode.all.easy.find_the_difference;

/*
      389. find the difference

https://leetcode.com/problems/find-the-difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

*/
class Solution {
  public char findTheDifference(String s, String t) {
    return ' ';
  }
}