package com.blogspot.ostas.leetcode.all.medium.minimum_size_subarray_in_infinite_array;

/*
      2875. minimum size subarray in infinite array

https://leetcode.com/problems/minimum-size-subarray-in-infinite-array

You are given a 0-indexed array nums and an integer target.
A 0-indexed array infinite_nums is generated by infinitely appending the elements of nums to itself.
Return the length of the shortest subarray of the array infinite_nums with a sum equal to target. If there is no such subarray return -1.

*/
class Solution {
  public int minSizeSubarray(int[] nums, int target) {
    return 0;
  }
}